export const phoneImages = [
  {
    name: 'Game',
    image: '/assets/images/landingpage/phone_game.svg',
    description:
      'Dive into the world of Izesan, where learning a new language feels like an epic adventure',
  },
  {
    name: 'Animation',
    image: '/assets/images/landingpage/phone_stories.svg',
    description:
      'Watch your learning experience unfold in vivid detail with our captivating video animations.',
  },
  {
    name: 'Stories',
    image: '/assets/images/landingpage/phone_animation.svg',
    description:
      "Embark on linguistic adventures with Izesan's stories that transport you to new worlds and cultures.",
  },
]

export const schoolLogo = [
  '/assets/images/landingpage/school_logo/school1.png',
  '/assets/images/landingpage/school_logo/school2.jpeg',
  '/assets/images/landingpage/school_logo/school3.jpeg',
  '/assets/images/landingpage/school_logo/school4.jpeg',
  '/assets/images/landingpage/school_logo/school5.png',
  '/assets/images/landingpage/school_logo/school6.webp',
  '/assets/images/landingpage/school_logo/school7.jpeg',
  '/assets/images/landingpage/school_logo/school8.png',
  '/assets/images/landingpage/school_logo/school9.png',
  '/assets/images/landingpage/school_logo/school10.jpeg',
  '/assets/images/landingpage/school_logo/school11.png',
  '/assets/images/landingpage/school_logo/school12.jpeg',
  '/assets/images/landingpage/school_logo/school13.png',
  '/assets/images/landingpage/school_logo/school14.jpeg',
  '/assets/images/landingpage/school_logo/school15.ipeg',
  '/assets/images/landingpage/school_logo/school16.png',
  '/assets/images/landingpage/school_logo/school17.png',
  '/assets/images/landingpage/school_logo/school18.jpeg',
  '/assets/images/landingpage/school_logo/school19.png',
  '/assets/images/landingpage/school_logo/school20.jpeg',
  '/assets/images/landingpage/school_logo/school21.png',
  '/assets/images/landingpage/school_logo/school22.jpeg',
  '/assets/images/landingpage/school_logo/school23.png',
  '/assets/images/landingpage/school_logo/school24.jpeg',
  '/assets/images/landingpage/school_logo/school25.jpeg',
  '/assets/images/landingpage/school_logo/school26.jpeg',
  '/assets/images/landingpage/school_logo/school27.jpeg',
  '/assets/images/landingpage/school_logo/school28.jpeg',
  '/assets/images/landingpage/school_logo/school29.jpeg',
  '/assets/images/landingpage/school_logo/school30.jpeg',
  '/assets/images/landingpage/school_logo/school31.jpeg',
  '/assets/images/landingpage/school_logo/school32.jpeg',
  '/assets/images/landingpage/school_logo/school33.jpeg',
  '/assets/images/landingpage/school_logo/school34.jpeg',
  '/assets/images/landingpage/school_logo/school35.jpeg',
  '/assets/images/landingpage/school_logo/school36.jpeg',
  '/assets/images/landingpage/school_logo/school37.jpeg',
  '/assets/images/landingpage/school_logo/school38.jpeg',
  '/assets/images/landingpage/school_logo/school39.jpeg',
  '/assets/images/landingpage/school_logo/school40.jpeg',
  '/assets/images/landingpage/school_logo/school41.jpeg',
  '/assets/images/landingpage/school_logo/school42.jpeg',
  '/assets/images/landingpage/school_logo/school43.jpeg',
  '/assets/images/landingpage/school_logo/school44.jpeg',
  '/assets/images/landingpage/school_logo/school45.jpeg',
  '/assets/images/landingpage/school_logo/school46.jpeg',
  '/assets/images/landingpage/school_logo/school47.png',
  '/assets/images/landingpage/school_logo/school48.jpeg',
  '/assets/images/landingpage/school_logo/school49.png',
  '/assets/images/landingpage/school_logo/school50.jpeg',
  '/assets/images/landingpage/school_logo/school51.jpeg',
  '/assets/images/landingpage/school_logo/school52.jpeg',
  '/assets/images/landingpage/school_logo/school53.png',
  '/assets/images/landingpage/school_logo/school54.png',
  '/assets/images/landingpage/school_logo/school55.jpeg',
  '/assets/images/landingpage/school_logo/school56.jpeg',


]
